import { vi } from 'vitest'
import '@testing-library/jest-dom'

// Mock window.api for renderer tests
const mockApi = {
  getState: vi.fn(),
  saveState: vi.fn(),
  scanWorkspace: vi.fn(),
  startProject: vi.fn(),
  stopProject: vi.fn(),
  getProcessStatuses: vi.fn().mockResolvedValue([]),
  getLogs: vi.fn(),
  openInBrowser: vi.fn(),
  detectSystemPorts: vi.fn().mockResolvedValue({}),
  killSystemProcess: vi.fn(),
  listWorkspaceFolders: vi.fn().mockResolvedValue([]),
  openInIde: vi.fn(),
  openInFinder: vi.fn(),
  openInTerminal: vi.fn(),
  getGitInfo: vi.fn().mockResolvedValue({ gitBranch: null, gitRemote: null }),
  getGitStatus: vi.fn(),
  getGitSyncStatus: vi.fn().mockResolvedValue({
    isGitRepo: false,
    baseBranch: null,
    currentBranch: null,
    commitsBehind: 0,
    commitsAhead: 0,
    uncommitted: 0,
    state: 'not-git',
  }),
  pullFolderToBase: vi.fn().mockResolvedValue({ success: true }),
  pullAllFoldersToBase: vi.fn().mockResolvedValue([]),
  startPullFolderToBase: vi.fn().mockResolvedValue({ started: true }),
  startPullAllFoldersToBase: vi.fn().mockResolvedValue({ started: true, count: 0 }),
  onGitPullFinished: vi.fn().mockReturnValue(() => {}),
  onGitPullBatchFinished: vi.fn().mockReturnValue(() => {}),
  airflowDiscover: vi.fn().mockResolvedValue({
    isRepo: false,
    repoRoot: null,
    apiUrl: null,
    uiPort: null,
    setupScriptExists: false,
  }),
  airflowHealth: vi.fn().mockResolvedValue({ ok: false }),
  airflowListDags: vi.fn().mockResolvedValue({ success: true, dags: [] }),
  airflowPatchDag: vi.fn().mockResolvedValue({ success: true }),
  airflowTriggerDag: vi.fn().mockResolvedValue({ success: true }),
  airflowListDagRuns: vi.fn().mockResolvedValue({ success: true, runs: [] }),
  airflowListTaskInstances: vi.fn().mockResolvedValue({ success: true, tasks: [] }),
  airflowGetTaskLog: vi.fn().mockResolvedValue({ success: true, log: '' }),
  openClaudeWorktree: vi.fn(),
  ptyCreate: vi.fn(),
  ptyWrite: vi.fn(),
  ptyResize: vi.fn(),
  ptyDestroy: vi.fn(),
  cleanupWorktree: vi.fn(),
  ptyListSessions: vi.fn(),
  listDirectory: vi.fn(),
  readFile: vi.fn(),
  searchFiles: vi.fn(),
  getWorktreeDiff: vi.fn(),
  detectClaudeSessionId: vi.fn(),
  saveTempImage: vi.fn(),
  selectFolder: vi.fn(),
  openBrowser: vi.fn(),
  closeBrowser: vi.fn(),
  isBrowserOpen: vi.fn(),
  onBrowserEvent: vi.fn().mockReturnValue(() => {}),
  onPtyData: vi.fn().mockReturnValue(() => {}),
  onPtyExit: vi.fn().mockReturnValue(() => {}),
  onStatuslineData: vi.fn().mockReturnValue(() => {}),
  onProcessLog: vi.fn().mockReturnValue(() => {}),
  onProcessStatusChanged: vi.fn().mockReturnValue(() => {}),
  pipelineStart: vi.fn(),
  pipelineCancel: vi.fn(),
  pipelineGetRuns: vi.fn(),
  pipelineGetConfig: vi.fn(),
  pipelineSetConfig: vi.fn(),
  onPipelineEvent: vi.fn().mockReturnValue(() => {}),
  rtkDetect: vi.fn().mockResolvedValue({ installed: false, version: null, hookActive: false, path: null }),
  rtkEnable: vi.fn().mockResolvedValue({ success: true, output: '' }),
  rtkDisable: vi.fn().mockResolvedValue({ success: true, output: '' }),
  rtkGain: vi.fn().mockResolvedValue(null),
  rtkSessionToggle: vi.fn().mockResolvedValue({ disabled: false }),
  rtkSessionStatus: vi.fn().mockResolvedValue({ disabled: false }),
  rtkSessionCleanup: vi.fn(),
  scanAgents: vi.fn(),
  getAgentLogs: vi.fn(),
  triggerAgent: vi.fn(),
  enhancerGetConfig: vi.fn().mockResolvedValue({ enabled: false, apiKey: '', model: 'gpt-4.1-nano', baseUrl: '' }),
  enhancerSetConfig: vi.fn().mockResolvedValue(undefined),
  enhancePrompt: vi.fn().mockResolvedValue(null),
  enhancerGetCost: vi.fn().mockResolvedValue({ totalUsd: 0, calls: 0 }),
  enhancerGetTotalCost: vi.fn().mockResolvedValue({ totalUsd: 0, calls: 0 }),
  scrollbackListRecoverable: vi.fn().mockResolvedValue([]),
  scrollbackRestore: vi.fn().mockResolvedValue(null),
  scrollbackDismiss: vi.fn().mockResolvedValue(undefined),
  scrollbackCleanupOld: vi.fn().mockResolvedValue(undefined),

  // Resource monitoring
  resourceGetSnapshot: vi.fn().mockResolvedValue({ timestamp: 0, sessions: [], host: { totalMemory: 0, freeMemory: 0, usedMemory: 0, memoryUsagePercent: 0, cpuCores: 1, loadAverage1m: 0 } }),
  resourceSubscribe: vi.fn().mockResolvedValue(undefined),
  resourceUnsubscribe: vi.fn().mockResolvedValue(undefined),
  onResourceUpdate: vi.fn().mockReturnValue(() => {}),

  // Workspace init progress
  onWorkspaceInitProgress: vi.fn().mockReturnValue(() => {}),
  workspaceInitCancel: vi.fn().mockResolvedValue(undefined),

  // Notifications
  notificationSetEnabled: vi.fn().mockResolvedValue(undefined),
  notificationSetQuietMode: vi.fn().mockResolvedValue(undefined),
  notificationGetSettings: vi.fn().mockResolvedValue({ enabled: true, quietMode: true }),
  onNotificationClicked: vi.fn().mockReturnValue(() => {}),

  // MCP & Skills
  mcpGetConfig: vi.fn().mockResolvedValue([]),
  mcpCheckStatus: vi.fn().mockResolvedValue({}),
  mcpSaveConfig: vi.fn().mockResolvedValue({ success: true }),
  mcpReadRawFile: vi.fn().mockResolvedValue({ success: true, content: '{\n  "mcpServers": {}\n}\n', exists: false }),
  mcpSaveRawFile: vi.fn().mockResolvedValue({ success: true }),
  mcpMergeServers: vi.fn().mockResolvedValue({ success: true }),
  skillsList: vi.fn().mockResolvedValue([]),
  createCommand: vi.fn().mockResolvedValue({ success: true }),
  deleteCommand: vi.fn().mockResolvedValue({ success: true }),
  // Active sessions
  activeSessionsSet: vi.fn().mockResolvedValue(undefined),
  activeSessionsUpdateClaudeId: vi.fn().mockResolvedValue(undefined),
  activeSessionsRemove: vi.fn().mockResolvedValue(undefined),
  activeSessionsGetAll: vi.fn().mockResolvedValue([]),
  activeSessionsSetActiveId: vi.fn().mockResolvedValue(undefined),
  activeSessionsGetActiveId: vi.fn().mockResolvedValue(null),
  activeSessionsUpdateMeta: vi.fn().mockResolvedValue(undefined),
  activeSessionsSetOrder: vi.fn().mockResolvedValue(undefined),
  activeSessionsGetUi: vi.fn().mockResolvedValue({ sessionOrder: [], gridMode: false, gridLayout: '1x1', gridSessionIds: [] }),
  activeSessionsSetUi: vi.fn().mockResolvedValue(undefined),
  systemCheck: vi.fn().mockResolvedValue({ node: { ok: true, version: 'v20' }, claude: { ok: true, version: '1.0' }, git: { ok: true, version: 'git' } }),
  appCheckUpdates: vi.fn().mockResolvedValue({ status: 'idle', error: null, version: null, percent: 0 }),
  appDownloadUpdate: vi.fn().mockResolvedValue({ status: 'idle', error: null, version: null, percent: 0 }),
  appInstallUpdate: vi.fn().mockResolvedValue(undefined),
  appGetUpdateStatus: vi.fn().mockResolvedValue({ status: 'idle', error: null, version: null, percent: 0 }),
  // Session history
  sessionHistoryScan: vi.fn().mockResolvedValue([]),
  sessionHistoryTitle: vi.fn().mockResolvedValue(null),
  // Session presets
  presetList: vi.fn().mockResolvedValue([]),
  presetCreate: vi.fn().mockResolvedValue({ id: 'new-preset', name: 'Test', createdAt: Date.now(), useCount: 0 }),
  presetUpdate: vi.fn().mockResolvedValue(null),
  presetDelete: vi.fn().mockResolvedValue(true),
  presetGetPinned: vi.fn().mockResolvedValue([]),
  presetGetRecent: vi.fn().mockResolvedValue([]),
  presetLaunch: vi.fn().mockResolvedValue({ success: true }),
  // Branches
  listBranches: vi.fn().mockResolvedValue({ current: null, branches: [] }),
  checkoutBranch: vi.fn().mockResolvedValue({ success: true }),
  findFilesByName: vi.fn().mockResolvedValue([]),
}

// Only set window.api in jsdom (renderer tests); Node main process tests have no window
if (typeof window !== 'undefined') {
  Object.defineProperty(window, 'api', {
    value: mockApi,
    writable: true,
  })
  const store = new Map<string, string>()
  Object.defineProperty(window, 'localStorage', {
    value: {
      getItem: (key: string) => store.get(key) ?? null,
      setItem: (key: string, val: string) => { store.set(key, val) },
      removeItem: (key: string) => { store.delete(key) },
      clear: () => { store.clear() },
    },
    writable: true,
  })
}
